# Basic
title: 冷雪
subtitle: Xue Leng
description: Welcome to my home!
# 头像里面的标题
avatarTitle: Ph.D in ZJU
# 头像里面的描述
avatarDesc: SDN / NFV
url: "http://lxv458.github.io"

# Comment
#comment:
 #   disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: Cold_Xue 
    github: lxv458
    # twitter: 
    mail: lengxue_2015@outlook.com
    linkedin: in/雪-冷-3549b111a

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
 #   id: UA-84134159-3   
 #   host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Resume

# Navigation buttons in the front page.s
nav:
#    - {title: Tag, description: tags, url: '/tags'} 
    - {title: Article, description: article, url: '/archive'}   
    - {title: 简历, description: 简历, url: '/about'}    
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


